name: 'Release Asset'
description: 'Upload files to a release'
inputs:
  file:
    description: The file to upload
    required: false
  files:
    description: A new line seperated list of files upload
    required: false
  pattern:
    description: Glob pattern of files to upload
    required: false
  github-token:
    description: The GitHub token used to create an authenticated client
    required: true
  release-url:
    description: The url of the release files are uploaded to
    required: false
  release-id:
    description: The ID of the release
    required: false
  allow-overwrite:
    description: Allow overwriting of existing files
    required: false
outputs:
  url:
    description: 'URL to the Release HTML Page'
runs:
  using: 'node12'
  main: 'main.js'
